// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.huskyui.rpc.model;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Message.MessageType messageType = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <code>.Message.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  Message.MessageType getMessageType();

  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  String getBody();
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
